### ISSUE TITLE
Implement comparator settings and messages

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/pysparc#32]

**Comment by davidfokkema** [comment]
This is nice, in theory. The hardware supports it, but as far as I know it is *still* not fully implemented for the regular setup. It was never used in any analysis. I'll reopen it if there is any need. Master/slave support is *much* higher on the list, and that is probably not going to happen.

**Comment by 153957** [comment]
The latest LabView version does support Comparator messages.
See the raw data for station 501, it should contain some comparator messages.
But still, as you say, it is not used yet, and only a handful of stations have the new software.
And only a small number of events per day will have use of the comparators.
Especially since most PMTs are non-linear, making it unlikely they will reach those comparator thresholds.

**Comment by davidfokkema** [comment]
I think this needs revisiting when the majority of stations support it and if there is a use case.

**Comment by 153957** [comment]
Agreed.
