### ISSUE TITLE
Implement n_peaks

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/pysparc#48]
Not yet implemented...

**Comment by 153957** [comment]
See [sapphire.analysis.process_traces.TraceObservables.n_peaks](https://github.com/HiSPARC/sapphire/blob/master/sapphire/analysis/process_traces.py#L131) for an example matching the implementation in the DAQ. However, it might not be the most efficient method..

**Comment by davidfokkema** [comment]
Thanks! I think it would be best to match the implementation. I will look into this!

**Comment by 153957** [comment]
Extra explanation, here is the text and illustration for this algorithm I originally made for my thesis:

-----

Most traces contain only a single pulse. However, sometimes multiple particles pass through a detector within the short time window of the trigger, and separated enough to be distinguishable in the trace. In order to find events with multiple pulses the number of peaks in a trace is determined. The algorithm starts at the start of a trace and when the signal values rise more than the low trigger threshold, in this case relative to the baseline, a peak is counted. When a peak has reached its apex and then lowers again the maximum value is remembered, the trace values needs to drop at least the value of the threshold before a new peak can start. For the next peak the signal value needs to rise at least the threshold value again, above the new local minimum since the previous peak

![n_peaks](https://user-images.githubusercontent.com/1433682/35096960-64cda24c-fc4e-11e7-99af-ba90254a5fa3.png)

[figure caption]
Illustrated definition of the number of peaks. The shown trace (gray) has multiple bumps, but not all are actual peaks. The thresholds the signal needs to cross to be counted as peak (red), and the threshold it needs to drop below before the next peak can start (blue) are shown. These thresholds follow the local minimum (green) and local maximum (purple). In this case two peaks are seen.
